'use strict';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const state={bpm:120,beats:4,denom:4,bars:4,stepsPerBar:16,steps:64,step:0,playing:false,timer:null,tool:'X',offset:0,grid:[],tapTimes:[],audio:null,unlocked:false};
function calcStepsPerBar(){return Math.max(1, Math.round(state.beats*(16/state.denom)));}
function resizeGrid(keep=true){state.stepsPerBar=calcStepsPerBar(); const newSteps=state.stepsPerBar*state.bars; const old=state.grid.slice(); state.steps=newSteps; state.grid=Array.from({length:newSteps},(_,i)=>keep&&old[i]?old[i]:'-'); state.step%=newSteps; renderAll();}
function initDefault(){state.grid.fill('-'); applyGrouping('6+6+6+4');}
function parseNums(txt){return String(txt).split(/[+\s,;/-]+/).map(n=>parseInt(n,10)).filter(n=>Number.isFinite(n)&&n>0&&n<=128)}
function applyGrouping(txt){const nums=parseNums(txt); state.grid.fill('-'); let p=(state.offset%state.steps+state.steps)%state.steps; for(const n of nums){state.grid[p]='X'; p=(p+n)%state.steps;} renderAll();}
function rollDice(){const rolls=Number($('#diceSeg .on')?.dataset.rolls||6); const nums=Array.from({length:rolls},()=>1+Math.floor(Math.random()*6)); $('#diceResult').textContent=nums.join(' '); $('#grouping').value=nums.join('+'); applyGrouping(nums.join('+'));}
function nextValue(v){return v==='-'?state.tool:'-'}
function unlockAudio(){if(!state.audio){state.audio=new (window.AudioContext||window.webkitAudioContext)()} state.audio.resume(); state.unlocked=true; $('#audioBtn').textContent='Audio attivo'; $('#audioBtn').classList.add('neon'); beep(700,.04,.05)}
function beep(freq=500,dur=.045,gain=.05){if(!state.audio||state.audio.state!=='running')return; const ctx=state.audio,o=ctx.createOscillator(),g=ctx.createGain(); o.type='square'; o.frequency.value=freq; g.gain.setValueAtTime(0.0001,ctx.currentTime); g.gain.exponentialRampToValueAtTime(gain,ctx.currentTime+.005); g.gain.exponentialRampToValueAtTime(0.0001,ctx.currentTime+dur); o.connect(g).connect(ctx.destination); o.start(); o.stop(ctx.currentTime+dur+.01)}
function sounds(){const s=state.step; if(s%state.stepsPerBar===0)beep(230,.055,.06); else if(s%4===0)beep(160,.035,.035); const v=state.grid[s]; if(v==='X')beep(920,.055,.075); if(v==='x')beep(720,.035,.035); if(v==='U')beep(1100,.035,.04)}
function advance(playSound=true){state.step=(state.step+1)%state.steps; if(playSound)sounds(); renderAll(false)}
function intervalMs(){return 60000/(state.bpm*4)}
function play(){unlockAudio(); stop(false); state.playing=true; $('#playBtn').textContent='▶ PLAYING'; sounds(); state.timer=setInterval(()=>advance(true),intervalMs()); renderAll(false)}
function stop(update=true){state.playing=false; if(state.timer)clearInterval(state.timer); state.timer=null; $('#playBtn').textContent='▶ PLAY'; if(update)renderAll(false)}
function reset(){stop(); state.step=0; renderAll(false)}
function tap(){const now=performance.now(); state.tapTimes=state.tapTimes.filter(t=>now-t<2200); state.tapTimes.push(now); if(state.tapTimes.length>=2){const diffs=[]; for(let i=1;i<state.tapTimes.length;i++)diffs.push(state.tapTimes[i]-state.tapTimes[i-1]); const avg=diffs.reduce((a,b)=>a+b,0)/diffs.length; state.bpm=Math.round(60000/avg); $('#bpm').value=state.bpm; if(state.playing)play();}}
function renderGrid(){const g=$('#grid'); g.innerHTML=''; g.style.gridTemplateColumns=`90px repeat(${state.steps},34px)`; const blank=document.createElement('div'); g.appendChild(blank); for(let i=0;i<state.steps;i++){const lab=document.createElement('div'); lab.className='countLabel'; const pos=i%state.stepsPerBar; lab.textContent=pos%4===0?String(Math.floor(pos/4)+1):['e','&','a'][pos%4-1]||'·'; g.appendChild(lab)}
 const rowLab=document.createElement('div'); rowLab.className='barTitle'; rowLab.textContent='RIFF'; g.appendChild(rowLab); for(let i=0;i<state.steps;i++){const c=document.createElement('div'); const v=state.grid[i]||'-'; c.className=`cell ${v==='-'?'':v} ${i===state.step?'playhead':''} ${i%state.stepsPerBar===0?'downbeat':''}`; c.textContent=v; c.title=`step ${i+1}`; c.onclick=()=>{state.grid[i]=nextValue(v); renderAll(false); if(state.unlocked){state.step=i; sounds();}}; g.appendChild(c)} }
function drawOrbit(){const canvas=$('#orbit'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,cx=w/2,cy=h/2; ctx.clearRect(0,0,w,h); ctx.fillStyle='#05070b'; ctx.fillRect(0,0,w,h); const r=210; const riffR=172; function circle(rad,color,width=3){ctx.beginPath();ctx.arc(cx,cy,rad,0,Math.PI*2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()} circle(r,'#38f26d88',4); circle(riffR,'#a75cff88',4); circle(75,'#a75cff44',3);
 for(let i=0;i<state.stepsPerBar;i++){const a=-Math.PI/2+i/state.stepsPerBar*Math.PI*2; const isQ=i%4===0; const x=cx+Math.cos(a)*(isQ?r:r-12), y=cy+Math.sin(a)*(isQ?r:r-12); ctx.beginPath();ctx.arc(x,y,isQ?7:2.5,0,Math.PI*2);ctx.fillStyle=isQ?'#38f26d':'#9ba3b4aa';ctx.fill(); if(isQ){ctx.fillStyle='#fff';ctx.font='bold 24px system-ui';ctx.textAlign='center';ctx.textBaseline='middle'; ctx.fillText(String(i/4+1),cx+Math.cos(a)*(r+36),cy+Math.sin(a)*(r+36));}}
 for(let i=0;i<state.steps;i++){if(state.grid[i]==='-')continue; const a=-Math.PI/2+i/state.steps*Math.PI*2; const x=cx+Math.cos(a)*riffR,y=cy+Math.sin(a)*riffR; ctx.beginPath();ctx.arc(x,y,state.grid[i]==='X'?8:5,0,Math.PI*2);ctx.fillStyle=state.grid[i]==='U'?'#29e9ff':state.grid[i]==='x'?'#a75cff':'#ff3da5';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=16;ctx.fill();ctx.shadowBlur=0;}
 const pulseA=-Math.PI/2+(state.step%state.stepsPerBar)/state.stepsPerBar*Math.PI*2; const riffA=-Math.PI/2+state.step/state.steps*Math.PI*2; function hand(a,len,color,width){ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*len,cy+Math.sin(a)*len);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.shadowColor=color;ctx.shadowBlur=18;ctx.stroke();ctx.shadowBlur=0} hand(pulseA,r-10,'#38f26d',7); hand(riffA,riffR-8,'#a75cff',7); ctx.beginPath();ctx.arc(cx,cy,20,0,Math.PI*2);ctx.fillStyle='#111923';ctx.fill();ctx.strokeStyle='#fff5';ctx.stroke(); }
function renderAll(full=true){$('#pulseLabel').textContent=`${state.beats}/${state.denom}`; $('#riffLabel').textContent=`${state.bars} battute`; $('#barCount').textContent=state.bars; $('#stepCount').textContent=state.steps; $('#currentStep').textContent=state.step+1; $('#offsetVal').textContent=state.offset; if(full)renderGrid(); else {renderGrid()} drawOrbit();}
function bind(){ $('#audioBtn').onclick=unlockAudio; $('#playBtn').onclick=play; $('#stopBtn').onclick=()=>stop(); $('#stepBtn').onclick=()=>{unlockAudio(); advance(true)}; $('#resetBtn').onclick=reset; $('#tapBtn').onclick=tap; $('#clearBtn').onclick=()=>{state.grid.fill('-');renderAll()}; $('#bpm').onchange=e=>{state.bpm=Math.max(30,Math.min(300,Number(e.target.value)||120));e.target.value=state.bpm;if(state.playing)play()}; $('#beats').onchange=e=>{state.beats=Math.max(1,Math.min(32,Number(e.target.value)||4));resizeGrid()}; $('#denom').onchange=e=>{state.denom=Number(e.target.value)||4;resizeGrid()}; $$('#barsSeg button').forEach(b=>b.onclick=()=>{$$('#barsSeg button').forEach(x=>x.classList.remove('on'));b.classList.add('on');state.bars=Number(b.dataset.bars);resizeGrid()}); $$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(x=>x.classList.remove('on'));b.classList.add('on');state.tool=b.dataset.tool}); $('#applyGroup').onclick=()=>applyGrouping($('#grouping').value); $$('#diceSeg button').forEach(b=>b.onclick=()=>{$$('#diceSeg button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}); $('#rollBtn').onclick=rollDice; $('#offsetMinus').onclick=()=>{state.offset=(state.offset-1+state.steps)%state.steps;renderAll(false)}; $('#offsetPlus').onclick=()=>{state.offset=(state.offset+1)%state.steps;renderAll(false)}; $('#helpBtn').onclick=()=>$('#help').showModal(); $('#closeHelp').onclick=()=>$('#help').close(); window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();state.playing?stop():play()} if(e.key==='ArrowRight')advance(true)})}
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
bind(); resizeGrid(false); initDefault();
