const $=id=>document.getElementById(id);const state={bars:5,stepsPerBar:16,step:0,playing:false,timer:null,grouping:[5,5,7,8],audio:null,taps:[],grid:[]};
function gcd(a,b){return b?gcd(b,a%b):a}function lcm(a,b){return a/gcd(a,b)*b}function total(){return state.bars*state.stepsPerBar}function cycleLen(){return state.grouping.reduce((a,b)=>a+b,0)||1}function realignBars(){return lcm(cycleLen(),state.stepsPerBar)/state.stepsPerBar}
function makeGrid(){state.grid=Array(total()).fill('-');let p=0;while(p<total()){state.grid[p]='A';for(const g of state.grouping){p+=g;if(p<total())state.grid[p]='A'}}renderGrid();updateText();drawOrbit()}
function renderGrid(){const g=$('grid');g.style.setProperty('--cols',Math.min(total(),80));g.innerHTML='';state.grid.forEach((v,i)=>{const d=document.createElement('button');d.className='cell '+(v==='A'?'accent':v==='X'?'hit':v==='U'?'up':'');d.textContent=v==='-'?'-':v;d.title=`step ${i+1}`;d.onclick=()=>{state.grid[i]=v==='-'?'X':v==='X'?'A':v==='A'?'U':'-';renderGrid();drawOrbit()};g.appendChild(d)})}
function updateText(){const rb=realignBars();$('targetBarsText').textContent=state.bars;$('gridTitle').textContent=`${state.bars} bars · ${total()} steps`;$('totalStepsInfo').textContent=total();$('realignInfo').textContent=`every ${rb} bars`;$('groupingDisplay').textContent=state.grouping.join(' + ');$('cycleInfo').textContent=`${cycleLen()} steps`; $('stepText').textContent=`${state.step+1} / ${total()}`}
function drawOrbit(){const c=$('orbit'),ctx=c.getContext('2d'),w=c.width,h=c.height,cx=w/2,cy=h/2+10,r=210;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#25314d';ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();for(let i=0;i<state.bars;i++){const a=-Math.PI/2+i/state.bars*Math.PI*2;const x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;ctx.fillStyle='#dfe7ff';ctx.font='20px system-ui';ctx.fillText(String(i+1),x-8,y+7)}for(let i=0;i<state.stepsPerBar;i++){const a=-Math.PI/2+i/state.stepsPerBar*Math.PI*2;ctx.strokeStyle=i%4===0?'#ac57ff':'#3c4968';ctx.beginPath();ctx.moveTo(cx+Math.cos(a)*(r-12),cy+Math.sin(a)*(r-12));ctx.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);ctx.stroke()}const barA=-Math.PI/2+(Math.floor(state.step/state.stepsPerBar)%state.bars)/state.bars*Math.PI*2;const pulseA=-Math.PI/2+(state.step%state.stepsPerBar)/state.stepsPerBar*Math.PI*2;const riffA=-Math.PI/2+(state.step%cycleLen())/cycleLen()*Math.PI*2;hand(barA,r-35,'#b344ff',8);hand(pulseA,r-65,'#25e6ff',5);hand(riffA,r-90,'#ffd22e',5);function hand(a,len,col,lw){ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.shadowColor=col;ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*len,cy+Math.sin(a)*len);ctx.stroke();ctx.shadowBlur=0}ctx.fillStyle='#fff';ctx.font='34px system-ui';ctx.textAlign='center';ctx.fillText('BAR',cx,cy-34);ctx.font='74px system-ui';ctx.fillText(`${Math.floor(state.step/state.stepsPerBar)%state.bars+1} / ${state.bars}`,cx,cy+46);ctx.font='16px system-ui';ctx.fillStyle='#b344ff';ctx.fillText(`realigns after ${realignBars()} bars`,cx,cy+90)}
function tick(){state.step=(state.step+1)%total();updateText();drawOrbit();renderPlaying();sound()}function renderPlaying(){document.querySelectorAll('.cell').forEach((e,i)=>e.classList.toggle('playing',i===state.step))}
function ensureAudio(){if(!state.audio)state.audio=new (window.AudioContext||window.webkitAudioContext)();if(state.audio.state==='suspended')state.audio.resume()}function beep(f=120,d=.045,g=.05){if(!state.audio)return;const o=state.audio.createOscillator(),a=state.audio.createGain();o.frequency.value=f;o.type='square';a.gain.value=g;o.connect(a);a.connect(state.audio.destination);o.start();o.stop(state.audio.currentTime+d)}function sound(){const v=state.grid[state.step];if(state.step%16===0)beep(220,.04,.05);if(v==='A')beep(900,.05,.08);else if(v==='X')beep(130,.045,.07);else if(v==='U')beep(520,.04,.05)}
$('play').onclick=()=>{ensureAudio();if(state.playing)return;state.playing=true;const bpm=+$('bpm').value||120;state.timer=setInterval(tick,60000/(bpm*4))};$('stop').onclick=()=>{state.playing=false;clearInterval(state.timer)};$('step').onclick=tick;$('clear').onclick=()=>{state.grid=Array(total()).fill('-');renderGrid();drawOrbit()};$('audio').onclick=ensureAudio;$('targetBars').oninput=e=>{state.bars=+e.target.value;makeGrid()};$('rolls').oninput=e=>$('rollsText').textContent=e.target.value;$('density').oninput=e=>$('densityText').textContent=e.target.value+'%';$('rollDice').onclick=()=>{const n=+$('rolls').value;state.grouping=Array.from({length:n},()=>3+Math.floor(Math.random()*5));$('diceResult').textContent=state.grouping.join(' + ');makeGrid()};$('autoGenerate').onclick=()=>{const target=+$('targetBars').value;let tries=0;do{const n=3+Math.floor(Math.random()*4);state.grouping=Array.from({length:n},()=>2+Math.floor(Math.random()*7));tries++}while(realignBars()!==target&&tries<800);$('diceResult').textContent=state.grouping.join(' + ');makeGrid()};$('fakeDetect').onclick=()=>{state.grouping=[3,3,2,5,3];makeGrid()};$('tap').onclick=()=>{const now=performance.now();state.taps.push(now);state.taps=state.taps.slice(-4);if(state.taps.length>1){let diffs=[];for(let i=1;i<state.taps.length;i++)diffs.push(state.taps[i]-state.taps[i-1]);$('bpm').value=Math.round(60000/(diffs.reduce((a,b)=>a+b,0)/diffs.length))}};$('exportMidi').onclick=()=>alert('Export MIDI placeholder: prossimo step');$('exportXml').onclick=()=>alert('MusicXML placeholder: prossimo step');
makeGrid();
