const $=id=>document.getElementById(id);
const state={bpm:120,num:4,den:4,bars:4,step:0,playing:false,timer:null,grid:[],group:[6,6,6],mode:'cycle',audio:null,dice:[],detected:[]};
const symbols=['-','x','X','A','U'];
function barSteps(){return state.num*(16/state.den)}
function displaySteps(){return Math.max(1,Math.round(barSteps()*state.bars))}
function riffLen(){return state.group.reduce((a,b)=>a+b,0)||1}
function gcd(a,b){a=Math.abs(a);b=Math.abs(b);while(b){[a,b]=[b,a%b]}return a||1}
function lcm(a,b){return Math.abs(a*b)/gcd(a,b)}
function setStatus(t){$('status').textContent=t}
function initGrid(){const n=displaySteps();state.grid=Array.from({length:n},(_,i)=>state.grid[i]||'-');renderAll()}
function parseGroup(){const g=$('grouping').value.split(/[+\s,]+/).map(x=>parseInt(x,10)).filter(x=>Number.isFinite(x)&&x>0&&x<=64);state.group=g.length?g:[4,4,4,4];$('grouping').value=state.group.join('+')}
function groupHits(limit,cycle=false){const hits=[];let pos=0;const len=riffLen();while(pos<limit){hits.push(pos);let acc=0;for(const g of state.group){acc+=g;const p=pos+acc;if(p<limit)hits.push(p)}pos+= cycle?len:len}return [...new Set(hits)].filter(x=>x<limit)}
function generateFromGroup(){parseGroup();const n=displaySteps();state.grid=Array(n).fill('-'); if(state.mode==='linear'){let p=0;while(p<n){state.grid[p]='A';for(const g of state.group){p+=g;if(p<n)state.grid[p]='A'} }} else {for(const p of groupHits(n,true))state.grid[p]='A'} state.step=0;renderAll();setStatus('Grouping generated')}
function rollDice(){const rolls=parseInt($('rolls').value,10);state.dice=Array.from({length:rolls},()=>1+Math.floor(Math.random()*6));$('diceOut').textContent=state.dice.join(' + ')}
function applyDice(){if(!state.dice.length)rollDice();$('grouping').value=state.dice.join('+');generateFromGroup()}
function renderGrid(){const n=displaySteps(),bs=barSteps();const grid=$('grid');grid.innerHTML='';grid.style.gridTemplateColumns=`repeat(${Math.min(16,n)}, minmax(34px,1fr))`;for(let i=0;i<n;i++){const d=document.createElement('button');d.className='cell';const v=state.grid[i]||'-';if(v==='x')d.classList.add('ghost'); if(v==='X')d.classList.add('chug'); if(v==='A')d.classList.add('accent'); if(v==='U')d.classList.add('up'); if(i===state.step%n)d.classList.add('playhead'); if(i%bs===0)d.classList.add('bar-start'); d.innerHTML=`<small>${labelFor(i,bs)}</small>${v}`; d.onclick=()=>{const idx=symbols.indexOf(state.grid[i]||'-');state.grid[i]=symbols[(idx+1)%symbols.length];renderAll();playCell(state.grid[i])}; grid.appendChild(d)} }
function labelFor(i,bs){const within=i%bs; const beat=Math.floor(within/4)+1; return ['','e','&','a'][within%4] || beat}
function renderMesh(){const bs=Math.round(barSteps()), rl=riffLen(); const align=lcm(bs,rl); $('riffCycle').textContent=`${rl}/16`; $('barCycle').textContent=`${bs}/16`; $('realign').textContent=`${align/bs} bars`; $('totalSteps').textContent=align; const track=$('alignTrack'); track.innerHTML=''; const hits=groupHits(align,true); for(let i=0;i<align;i++){const c=document.createElement('div');c.className='align-cell'; if(i%bs===0)c.classList.add('bar'); if(hits.includes(i))c.classList.add('hit'); if(i===0||i===align)c.classList.add('realign'); if(i===state.step%align)c.classList.add('active'); track.appendChild(c)} }
function drawOrbit(){const canvas=$('orbit'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,cx=w/2,cy=h/2;ctx.clearRect(0,0,w,h);ctx.lineCap='round';const bs=barSteps(),rl=riffLen();drawCircle(230,'#23314f');drawCircle(168,'#352547');for(let i=0;i<bs;i++){const a=-Math.PI/2+i/bs*2*Math.PI;dot(cx+Math.cos(a)*230,cy+Math.sin(a)*230,i%4===0?6:2,i%4===0?'#34e8ff':'#415273')}const hits=groupHits(rl,true).filter(x=>x<rl);for(const p of hits){const a=-Math.PI/2+p/rl*2*Math.PI;dot(cx+Math.cos(a)*168,cy+Math.sin(a)*168,7,'#75ff66')}const pa=-Math.PI/2+(state.step%bs)/bs*2*Math.PI,ra=-Math.PI/2+(state.step%rl)/rl*2*Math.PI;hand(pa,230,'#34e8ff',5);hand(ra,168,'#ff4fd8',5);dot(cx,cy,8,'#ffb13b');ctx.fillStyle='#f4f7ff';ctx.font='900 34px system-ui';ctx.textAlign='center';ctx.fillText(`${rl}/16`,cx,cy-8);ctx.font='700 13px system-ui';ctx.fillStyle='#91a0b8';ctx.fillText(`returns after ${lcm(bs,rl)/bs} bars`,cx,cy+18);function drawCircle(r,col){ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle=col;ctx.lineWidth=3;ctx.stroke()}function hand(a,r,col,lw){ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.shadowColor=col;ctx.shadowBlur=18;ctx.stroke();ctx.shadowBlur=0}function dot(x,y,r,col){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=col;ctx.shadowColor=col;ctx.shadowBlur=12;ctx.fill();ctx.shadowBlur=0}}
function renderAll(){renderGrid();renderMesh();drawOrbit()}
function ensureAudio(){if(!state.audio){state.audio=new (window.AudioContext||window.webkitAudioContext)()} if(state.audio.state==='suspended')state.audio.resume();}
function tone(freq,dur=0.045,type='square',gain=.06){if(!state.audio)return;const ctx=state.audio,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(0.0001,ctx.currentTime+dur);o.stop(ctx.currentTime+dur)}
function playCell(v){if(v==='A')tone(1200,.06,'square',.08);else if(v==='X')tone(95,.055,'sawtooth',.08);else if(v==='x')tone(120,.035,'triangle',.035);else if(v==='U')tone(650,.04,'square',.045)}
function tick(){const bs=barSteps(); if(state.step%bs===0)tone(880,.035,'square',.04); else if(state.step%4===0)tone(440,.025,'square',.025); playCell(state.grid[state.step%state.grid.length]); state.step=(state.step+1)%displaySteps(); renderAll()}
function play(){ensureAudio(); if(state.playing)return; state.playing=true; const interval=60000/state.bpm/4; state.timer=setInterval(tick,interval); setStatus('Playing')}
function stop(){state.playing=false;clearInterval(state.timer);state.timer=null;setStatus('Stopped')}
let taps=[];function tap(){const now=performance.now();taps=taps.filter(t=>now-t<2500);taps.push(now);if(taps.length>=2){const diffs=taps.slice(1).map((t,i)=>t-taps[i]);const avg=diffs.reduce((a,b)=>a+b,0)/diffs.length;state.bpm=Math.round(60000/avg);$('bpm').value=state.bpm;setStatus(`Tap ${state.bpm} BPM`)}}
async function analyzeAudio(){const f=$('file').files[0]; if(!f){setStatus('Choose audio first');return} setStatus('Analyzing audio...'); const arr=await f.arrayBuffer(); const ctx=new (window.OfflineAudioContext||window.webkitOfflineAudioContext)(1,1,44100); const buf=await ctx.decodeAudioData(arr.slice(0)); const data=buf.getChannelData(0); const sr=buf.sampleRate; const win=Math.floor(sr*0.025), hop=Math.floor(sr*0.0125); let env=[]; for(let i=0;i<data.length-win;i+=hop){let sum=0; for(let j=0;j<win;j++){sum+=Math.abs(data[i+j])} env.push(sum/win)} let flux=[]; for(let i=1;i<env.length;i++)flux.push(Math.max(0,env[i]-env[i-1])); const mean=flux.reduce((a,b)=>a+b,0)/flux.length; const thresh=mean*3.5; let hits=[]; let last=-999; for(let i=1;i<flux.length-1;i++){if(flux[i]>thresh && flux[i]>flux[i-1] && flux[i]>flux[i+1] && i-last>4){hits.push(i*hop/sr);last=i}} state.detected=hits; $('detected').textContent = hits.length? `${hits.length} hits detected: `+hits.slice(0,24).map(x=>x.toFixed(2)+'s').join(', ')+(hits.length>24?'...':'') : 'No clear hits found.'; setStatus('Audio analyzed')}
function useDetected(){if(!state.detected.length){setStatus('No detected hits');return} const n=displaySteps(); state.grid=Array(n).fill('-'); const dur=state.detected[state.detected.length-1]-state.detected[0] || 1; for(const t of state.detected){const idx=Math.round(((t-state.detected[0])/dur)*(n-1)); if(idx>=0&&idx<n)state.grid[idx]='A'} renderAll(); setStatus('Detected hits mapped to grid')}
function bind(){['bpm','num','den','bars'].forEach(id=>$(id).onchange=()=>{state.bpm=+$('bpm').value;state.num=+$('num').value;state.den=+$('den').value;state.bars=+$('bars').value;initGrid()});document.querySelectorAll('input[name=mode]').forEach(r=>r.onchange=()=>{state.mode=r.value;generateFromGroup()});$('audio').onclick=()=>{ensureAudio();tone(660);setStatus('Audio ready')};$('play').onclick=play;$('stop').onclick=stop;$('reset').onclick=()=>{state.step=0;renderAll();setStatus('Reset')};$('step').onclick=()=>{ensureAudio();tick();setStatus('Step')};$('tap').onclick=tap;$('dice').onclick=rollDice;$('applyDice').onclick=applyDice;$('applyGroup').onclick=generateFromGroup;$('analyze').onclick=analyzeAudio;$('useDetected').onclick=useDetected}
bind();initGrid();generateFromGroup();
