const $ = (id)=>document.getElementById(id);
const state={bpm:120,num:4,den:4,bars:4,step:0,playing:false,timer:null,audio:null,pattern:[],grouping:[6,6,6],tap:[],cycleBars:1};
const symbols=['-','X','x','U'];
function barSteps(){return Math.round(state.num*(16/state.den));}
function totalSteps(){return barSteps()*state.bars;}
function gcd(a,b){a=Math.abs(a);b=Math.abs(b);while(b)[a,b]=[b,a%b];return a||1}
function lcm(a,b){return Math.abs(a*b)/gcd(a,b)}
function parseGrouping(){const arr=$('grouping').value.split(/[+ ,]+/).map(Number).filter(n=>Number.isFinite(n)&&n>0);state.grouping=arr.length?arr:[4];return state.grouping}
function riffLen(){return parseGrouping().reduce((a,b)=>a+b,0)}
function computeCycleBars(){const bs=barSteps(), rl=riffLen(); state.cycleBars=Math.max(1,lcm(bs,rl)/bs); $('cycleRead').textContent=`Bars to cycle: ${state.cycleBars}  •  cycle ${rl}/16`; updateBarsDropdown(); return state.cycleBars}
function buildPatternFromGrouping(steps=totalSteps()){parseGrouping(); state.pattern=Array(steps).fill('-'); let pos=0, i=0; while(pos<steps){state.pattern[pos]='X'; pos += state.grouping[i%state.grouping.length]; i++;} }
function ensurePattern(){const n=totalSteps(); if(!state.pattern.length) buildPatternFromGrouping(n); if(state.pattern.length<n){const old=state.pattern.slice(); for(let i=state.pattern.length;i<n;i++) state.pattern[i]=old[i%old.length]||'-';} if(state.pattern.length>n) state.pattern=state.pattern.slice(0,n)}
function updateBarsDropdown(){const sel=$('bars'), cur=state.bars; const values=[1,2,3,4,5,6,7,8,9,10,11,12,16,24,32,state.cycleBars].filter((v,i,a)=>v>0&&a.indexOf(v)===i).sort((a,b)=>a-b); sel.innerHTML=''; values.forEach(v=>{const o=document.createElement('option'); o.value=v; o.textContent=v===state.cycleBars?`${v} bars — cycle`:`${v} bars`; sel.appendChild(o)}); sel.value=String(cur);}
function renderGrid(){ensurePattern(); const grid=$('grid'); grid.innerHTML=''; grid.style.gridTemplateColumns=`repeat(${barSteps()}, minmax(42px, 1fr))`; state.pattern.forEach((s,i)=>{const d=document.createElement('button'); d.className=`cell ${s==='-'?'rest':s} ${i%4===0?'beat':''} ${i===state.step%state.pattern.length?'active':''}`; d.innerHTML=`<span class="label">${gridLabel(i)}</span>${s}`; d.onclick=()=>{const idx=symbols.indexOf(state.pattern[i]); state.pattern[i]=symbols[(idx+1)%symbols.length]; renderAll(false)}; grid.appendChild(d)}); $('stepsRead').textContent=`${totalSteps()} sixteenths • ${state.bars} bars`;}
function gridLabel(i){const bs=barSteps(); const inBar=i%bs; const beat=Math.floor(inBar/4)+1; const sub=['','e','&','a'][inBar%4]||''; return inBar%4===0?String(beat):sub}
function drawOrbit(){const c=$('orbit'), ctx=c.getContext('2d'), w=c.width,h=c.height,cx=w/2,cy=h/2; ctx.clearRect(0,0,w,h); const R=230; ctx.lineWidth=3; ctx.strokeStyle='#22334b'; ctx.beginPath(); ctx.arc(cx,cy,R,0,Math.PI*2); ctx.stroke(); ctx.strokeStyle='#2e214c'; ctx.beginPath(); ctx.arc(cx,cy,R-56,0,Math.PI*2); ctx.stroke(); const bars=state.cycleBars||1; ctx.font='14px Inter, Arial'; ctx.textAlign='center'; ctx.textBaseline='middle'; for(let b=1;b<=bars;b++){const a=-Math.PI/2+(b-1)/bars*Math.PI*2; const major=bars<=24||b===1||b===bars||b%Math.ceil(bars/12)===0; const r1=major?R-8:R-3, r2=major?R+10:R+4; lineAt(a,r1,r2,major?'#71ff7b':'#38506d',major?2:1); if(major){ctx.fillStyle='#8ea0b8'; ctx.fillText(String(b),cx+Math.cos(a)*(R+28),cy+Math.sin(a)*(R+28));}}
 const bs=barSteps(), rl=riffLen(); const global=state.step; const curBar=Math.floor((global% (bars*bs))/bs)+1; $('barRead').textContent=`BAR ${curBar}/${bars}`;
 const pulseA=-Math.PI/2+((global%bs)/bs)*Math.PI*2; const riffA=-Math.PI/2+((global%rl)/rl)*Math.PI*2; const barA=-Math.PI/2+((curBar-1)/bars)*Math.PI*2; hand(barA,R-5,'#ffcb5b',5); hand(pulseA,R-35,'#71ff7b',4); hand(riffA,R-90,'#b36bff',4); ctx.fillStyle='#eef7ff'; ctx.font='800 34px Inter, Arial'; ctx.fillText(`BAR ${curBar}/${bars}`,cx,cy-8); ctx.fillStyle='#8ea0b8'; ctx.font='15px Inter, Arial'; ctx.fillText(`riff ${rl}/16 • returns in ${bars} bars`,cx,cy+28);
 function lineAt(a,r1,r2,col,lw){ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.beginPath();ctx.moveTo(cx+Math.cos(a)*r1,cy+Math.sin(a)*r1);ctx.lineTo(cx+Math.cos(a)*r2,cy+Math.sin(a)*r2);ctx.stroke()}
 function hand(a,r,col,lw){ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.shadowColor=col;ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=col;ctx.beginPath();ctx.arc(cx+Math.cos(a)*r,cy+Math.sin(a)*r,8,0,Math.PI*2);ctx.fill()}}
function renderAll(rebuild=true){state.bpm=+$('bpm').value||120; state.num=+$('num').value||4; state.den=+$('den').value||4; if(rebuild) computeCycleBars(); ensurePattern(); renderGrid(); drawOrbit();}
function tick(){ensurePattern(); const s=state.pattern[state.step%state.pattern.length]; if(s!=='-') playSound(s); state.step++; renderAll(false)}
function start(){if(state.playing)return; unlockAudio(); state.playing=true; const ms=60000/state.bpm/4; state.timer=setInterval(tick,ms)}
function stop(){state.playing=false; clearInterval(state.timer)}
function reset(){stop(); state.step=0; renderAll(false)}
function unlockAudio(){if(!state.audio){state.audio=new (window.AudioContext||window.webkitAudioContext)()} if(state.audio.state==='suspended')state.audio.resume()}
function playSound(s){if(!state.audio)return; const ac=state.audio, o=ac.createOscillator(), g=ac.createGain(); o.type='square'; o.frequency.value=s==='X'?95:s==='x'?150:260; g.gain.setValueAtTime(s==='X'?0.16:0.09,ac.currentTime); g.gain.exponentialRampToValueAtTime(0.001,ac.currentTime+0.055); o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+0.06)}
$('audio').onclick=()=>{unlockAudio();$('audio').textContent='AUDIO READY'};$('play').onclick=start;$('stop').onclick=stop;$('reset').onclick=reset;$('step').onclick=()=>tick();$('fit').onclick=()=>{computeCycleBars();state.bars=state.cycleBars;$('bars').value=state.bars;buildPatternFromGrouping(totalSteps());renderAll(false)};
$('bars').onchange=()=>{state.bars=+$('bars').value; ensurePattern(); renderAll(false)};['bpm','num','den','grouping'].forEach(id=>$(id).onchange=()=>{computeCycleBars();buildPatternFromGrouping(totalSteps());renderAll(false)});
$('diceBtn').onclick=()=>{const n=Math.max(3,Math.min(6,+$('rolls').value||6)); const vals=Array.from({length:n},()=>1+Math.floor(Math.random()*6)); $('grouping').value=vals.join('+'); computeCycleBars(); buildPatternFromGrouping(totalSteps()); renderAll(false)};
$('genTarget').onclick=()=>{const target=Math.max(1,+$('target').value||4), bs=barSteps(); let candidates=[]; for(let len=3; len<=bs*target; len++){ if(lcm(bs,len)/bs===target) candidates.push(len)} const len=candidates[Math.floor(Math.random()*candidates.length)]||target*bs-1; let parts=[], left=len; while(left>0){const v=Math.min(left, 2+Math.floor(Math.random()*6)); parts.push(v); left-=v} $('grouping').value=parts.join('+'); computeCycleBars(); state.bars=target; updateBarsDropdown(); $('bars').value=state.bars; buildPatternFromGrouping(totalSteps()); renderAll(false)};
$('tap').onclick=()=>{const now=performance.now(); state.tap=state.tap.filter(t=>now-t<2200); state.tap.push(now); if(state.tap.length>1){const diffs=state.tap.slice(1).map((t,i)=>t-state.tap[i]); const avg=diffs.reduce((a,b)=>a+b,0)/diffs.length; $('bpm').value=Math.round(60000/avg); renderAll(false)}};
computeCycleBars(); buildPatternFromGrouping(totalSteps()); renderAll(false);
